//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_product = new HashSet<order_product>();
            this.product_img_url = new HashSet<product_img_url>();
        }
    
        public string name { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> deleted { get; set; }
        public int price { get; set; }
        public int price_sale { get; set; }
        public int id { get; set; }
        public int quantity { get; set; }
        public string description { get; set; }
        public Nullable<bool> isHot { get; set; }
        public Nullable<int> create_at { get; set; }
        public Nullable<int> rate { get; set; }
        public string avatar_url { get; set; }
        public Nullable<int> category_id { get; set; }
        public string create_user { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_product> order_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_img_url> product_img_url { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }

        public HttpPostedFileBase[] multiImg { get; set; }
    }
}
